version: "2"
linters:
  enable:
    - errcheck
    - govet
  exclusions:
    rules:
      - text: "ST1005:"
        linters:
          - staticcheck
      - text: "ST1006:"
        linters:
          - staticcheck
      - text: "Error return value of `.*\\.Close` is not checked"
        linters:
          - errcheck
      - text: Error return value of `os.Setenv` is not checked
        linters:
          - errcheck
