FROM archlinux:latest

WORKDIR /root

COPY . /root/.dotfiles

RUN yes | pacman -Syu
RUN yes | pacman -S git wget curl jq stow zsh python

RUN yes | pacman -S go
# RUN yes | pacman -S zig
# RUN yes | pacman -S odin

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN wget -qO- "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh" | bash
