FROM archlinux/archlinux:latest

RUN \
  pacman -Syu --noconfirm && \
  pacman -S --noconfirm \
  base-devel \
  git \
  vim \
  curl \
  wget \
  stow \
  go \
  bash \
  sudo \
  man-db \
  man-pages && \
  pacman -Syu --noconfirm

RUN \
  useradd -m -G wheel -s /bin/bash user && \
  echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER user
WORKDIR /home/user

RUN mkdir -p .config .local/bin .local/share

ENV HOME=/home/user
ENV USER=user

CMD [ "/bin/bash" ]

