FROM archlinux/archlinux:latest

RUN \
  pacman -Syu --noconfirm && \
  pacman -S --noconfirm \
  base-devel \
  git \
  lua \
  vim \
  nvim \
  curl \
  wget \
  stow \
  go \
  jq \
  fd \
  zip \
  fzf \
  zsh \
  ripgrep \
  unzip \
  bash \
  sudo \
  man-db \
  man-pages && \
  pacman -Syu --noconfirm

RUN \
  useradd -m -G wheel -s /bin/bash user && \
  echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER user
WORKDIR /home/user

# Install Oh-My-Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install Homebrew as non-root user with NONINTERACTIVE flag
RUN NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Make Go binaries available in current layer
ENV PATH="/home/user/go/bin:${PATH}"

RUN go install github.com/aquaproj/aqua/v2/cmd/aqua@latest
RUN mkdir -p .config .local/bin .local/share
RUN touch .zshrc

ENV HOME=/home/user
ENV USER=user

CMD [ "/bin/bash" ]
