#!/usr/bin/env bash
use_local=false
local_dir=".dotfiles"

if [[ "$2" = "local" ]]; then
  use_local=true
fi

# Must be BASH to support prompting properly.
if [ -z "$BASH_VERSION" ]; then
    echo "This script requires bash" >&2
    exit 1
fi

DIR="${1}"
BASE="${HOME}/${DIR}"
BIN="${BASE}/.bin"

# Allows me to invoke the installation from
# local scripts instead of through GitHub.
if [[ "$use_local" = true ]]; then
  BIN="${HOME}/${local_dir}/.bin"
fi

PACMAN_INSTALL="pacman-install.sh"
BREW_INSTALL="brew-install.sh"
MIXED_INSTALL="mixed-install.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
DIM='\e[2m'
BOLD='\e[1m'

# Clear the color
CLEAR='\033[0m'

# Installation state.
has_error=false
has_pacman=false
has_brew=false
can_install=false

function red { printf "${RED}$@${CLEAR}\n"; }
function green { printf "${GREEN}$@${CLEAR}\n"; }
function yellow { printf "${YELLOW}$@${CLEAR}\n"; }

function dim { printf "${DIM}$@${CLEAR}\n"; }
function bold { printf "${BOLD}$@${CLEAR}\n"; }

function separator {
  echo -e "$(dim "________________________________________________")"
}

function is_yes {
  case "${1,,}" in
    y|yes|true|t|on|1) return 0 ;;
    *) return 1 ;;
  esac
}

function is_no {
  case "${1,,}" in
    n|no|false|f|off|0) return 0 ;;
    *) return 1 ;;
  esac
}

function confirm {
  local prompt="$1"
  local default="${2,,}"
  local response

  while true; do
    printf "%s " "$prompt" >/dev/tty
    read -r response </dev/tty
    
    # Use default if response is empty
    if [ -z "$response" ]; then
      response="$default"
    fi

    if is_yes "$response"; then
      return 0
    elif is_no "$response"; then
      return 1
    else
      printf "Please answer yes or no.\n" >/dev/tty
    fi
  done
}

function check {
  is_required=$1
  pkg=$2

  printf "$pkg\t"

  which $pkg &>/dev/null; if [[ $? != 0 ]]; then
    msg="$(red "❌") "

    if [ "$is_required" == true ]; then
      msg+="$(dim "(missing required package)")"
    else
      msg+="$(dim "(missing, but NOT required)")"
    fi

    echo -e "${msg}"

    if [ "$is_required" == true ]; then
      if [ "$has_error" == false ]; then
        has_error=true
      fi
    fi
  else
    echo -e "$(green "✔️")  $(dim "(found)")"

    if [[ $pkg == *"pacman"* ]]; then
      has_pacman=true
    fi

    if [[ $pkg == *"brew"* ]]; then
      has_brew=true
    fi
  fi
}

separator
echo -e "$(bold "Checking required package(s)")"

# Check for the required packages to be installed
# in order to run the installation script.
check false "pacman"
check false "brew"
check true "git"

# If an error was triggered in the initial package(s)
# check, then the installation won't work.
if [ "$has_error" == true ]; then
  exit 1
fi

echo ""
separator

# Showing any system information before starting
# the installation process.
echo -e "$(bold "System Configuration")"
printf "os\t${OSTYPE}\n"

if [ ! -d "$BASE" ]; then
  # If there is not base directory, we can trigger
  # the installation script type.
  can_install=true
else
  # If is an existing base directory we need to
  # make sure it's okay to remove it before starting
  # the installation.
  echo ""
  separator

  echo "$(bold $(yellow "WARNING"))"
  echo "Path already exists!"
  echo ""
  echo "$(bold $BASE)"
  echo ""

  if confirm "Do you want to continue? (y/N)" "n"; then
    can_install=true
    rm -rfv ${BASE}
  else
    echo "Nothing to be installed..."
    exit 0
  fi
fi

# If we can perform the installation, we check
# the system package flags we checked for for use
# that to know which installation script to run.
if [[ "$can_install" = true ]]; then
  echo ""
  separator
  git clone https://github.com/jgttech/dotfiles ${BASE}

  echo ""
  separator
  if [[ "$has_pacman" = true && "$has_brew" = false ]]; then
    ${BIN}/${PACMAN_INSTALL} ${BASE}
  elif [[ "$has_pacman" = false && "$has_brew" = true ]]; then
    ${BIN}/${BREW_INSTALL} ${BASE}
  elif [[ "$has_pacman" = true && "$has_brew" = true ]]; then
    ${BIN}/${MIXED_INSTALL} ${BASE}
  fi
fi
