#!/usr/bin/env python
import argparse
from os import path, getcwd
from subprocess import call

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("-B", "--binary", action="store", dest="bin", required=True, type=str)

  args = parser.parse_args()
  cwd = path.join(getcwd(), "tools/go")

  call(f"go build -o ../../.build/bin/{args.bin} main.go", shell=True, cwd=cwd)
