#!/usr/bin/env bash
set -euo pipefail

wd=`pwd`
base=$HOME/.dotfiles
bin=$base/.bin/dotfiles

function installed {
  command -v $1 &> /dev/null
}

#####################################
# Git
#
if ! installed git; then
  echo "Git must be installed!"
  exit 1
fi

if [[ ! -d "$base" ]]; then
  git clone https://github.com/jgttech/dotfiles.git $base
else
  cd $base
  git pull
  cd $wd
fi

#####################################
# Homebrew

if ! installed brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  brew --version
fi

if ! installed brew; then
  echo "Error: Unable to detect Homebrew installation."
  exit 1
fi

#####################################
# Go lang

if ! installed go; then
  brew install go
else
  go version

  # Fuck Google and their telemtry.
  go install golang.org/x/telemetry/cmd/gotelemetry@latest &> /dev/null
  go telemetry off &> /dev/null

  # Fuck Google and their telemtry.
  rm -rfv ~/.config/go/telemetry &> /dev/null
fi

if ! installed go; then
  echo "Error: Unable to detect Go installation."
  exit 1
fi

#####################################
# Build the Go binary and run it.

wd=`pwd`

cd $base/.bin
go build .

cd $wd

$bin install

echo "Done"
