#!/usr/bin/env bash
base=$HOME/.dotfiles

git clone https://github.com/jgttech/dotfiles.git $base

if ! command -v brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew installed!"
fi

if ! command -v go > /dev/null; then
  brew install go
else
  echo "Go installed!"
  go version
fi
