#!/usr/bin/env bash
base=$1
local_dir=".dotfiles"

if [[ "$2" = "local" ]]; then
  base="$HOME/$local_dir"
fi

bin="$base/.bin"
utils="$bin/utils"
install="$bin/install"

source "$utils/colors.sh"
source "$utils/separator.sh"
source "$utils/section.sh"
source "$utils/can_install.sh"

# Begin installation
yay_dir="$HOME/.yay"

function yay_install {
  local target=${2:-$1}

  if can_install "$target"; then
    echo ""
    yay -S $1 < /dev/tty
  fi
}

function pacman_install {
  local target=${2:-$1}

  if can_install "$target"; then
    echo ""
    sudo pacman -S $1 < /dev/tty
  fi
}

pacman -Q | grep "zsh" &>/dev/null; if [[ $? != 0 ]]; then
  echo "Please install and perform the initial"
  echo "ZSH setup process and then re-run this"
  echo "installation script."

  exit 1
fi

section "Installing packages..."

if can_install "yay"; then
  echo ""
  sudo pacman -S --needed git base-devel < /dev/tty
  git clone https://aur.archlinux.org/yay.git $yay_dir
  cd $yay_dir
  makepkg -si
fi

pacman_install "tmux"
pacman_install "stow"
yay_install "fswatch"
yay_install "python"
yay_install "python-pipx"
yay_install "ruby"
yay_install "perl"
yay_install "tree-sitter"
yay_install "php"
yay_install "rust"
yay_install "luarocks"
yay_install "odin-bin"
yay_install "go"

if [ ! -d "$HOME/.nvm" ]; then
  echo -e "$(red "❌") nvm $(dim "(not installed)")" 
  echo ""
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
else
  echo -e "$(green "✔️") nvm $(dim "(already installed)")"
fi

pipx list | grep "black" &>/dev/null; if [[ $? != 0 ]]; then
  echo -e "$(red "❌") black (pipx) $(dim "(not installed)")" 
  echo ""
  pipx install black
else
  echo -e "$(green "✔️") black (pipx) $(dim "(already installed)")"
fi

which brew &>/dev/null; if [[ $? != 0 ]]; then
  echo -e "$(red "❌") brew $(dim "(not installed)")" 
  echo ""
  echo -e $(bold $(yellow "WARNING"))
  echo "There may be additional instructions"
  echo "that Homebrew needs to be performed to"
  echo "complete the installation."
  echo ""

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo -e "$(green "✔️") brew $(dim "(already installed)")"
  echo ""
  brew install cffi < /dev/tty
fi

echo ""
go install golang.org/x/telemetry/cmd/gotelemetry@latest
go telemetry off
rm -rfv ~/.config/go/telemetry
