#!/usr/bin/env bash
set -euo pipefail

wd=`pwd`
base=$HOME/.dotfiles
bin=$base/.bin/build/dotfiles

function installed {
  command -v $1 &> /dev/null
}

#####################################
# Git
#
if ! installed git; then
  echo "Git must be installed!"
  exit 1
fi

if [[ ! -d "$base" ]]; then
  git clone https://github.com/jgttech/dotfiles.git $base
else
  cd $base
  git pull
  cd $wd
fi

#####################################
# Go lang

if ! installed go; then
  echo "Please install Go and re-run the install"
  exit 1
else
  go version

  # Fuck Google and their telemtry.
  go install golang.org/x/telemetry/cmd/gotelemetry@latest &> /dev/null
  go telemetry off &> /dev/null

  # Fuck Google and their telemtry.
  rm -rfv ~/.config/go/telemetry &> /dev/null
fi

if ! installed go; then
  echo "Error: Unable to detect Go installation."
  exit 1
fi

#####################################
# Build the Go binary and run it.

wd=`pwd`

cd $base/.bin
go build -o build/dotfiles .

cd $wd

$bin install

echo "Done"
